repos:
  - repo: local
    hooks:
    - id: system
      name: fmt
      entry: make fmt
      language: system
      types: [python]
    - id: system
      name: lint
      entry: make lint
      language: system
      types: [python]
