default: &default
  working_directory: ~/abeja-platform-sdk
  docker:
    - image: circleci/python:3.5

# Job Steps
test_step: &test_step
  - checkout
  - run:
      name: Install Dependencies
      environment:
        - PIPENV_VENV_IN_PROJECT: 1
      command: |
        sudo pip install poetry
        poetry install
  - run:
      name: Test
      command: |
        make test
  # NOTE: need to fix test cases, because these are not stable.
  # - run:
  #     name: Integration Test
  #     command: |
  #       make integration_test

install-release-dependencies: &install-release-dependencies
  run:
    name: Install Dependencies
    command: |
      sudo apt-get update
      poetry install

run-release: &run-release
  run:
    name: Deploy
    command: |
      sudo -E make release

trigger-system-test: &trigger-system-test
  run:
    name: TriggerSystemTest
    command: |
      poetry run python tools/trigger_build_system_test.py

release: &release
  - checkout
  - *install-release-dependencies
  - *run-release
  - *trigger-system-test

release-rc: &release-rc
  - checkout
  - *install-release-dependencies
  - run: poetry version $(PYTHONPATH=./ poetry run python tools/add_rc_version.py)
  - *run-release
  - *trigger-system-test

# Jobs
version: 2
jobs:
  codetest:
    <<: *default
    steps: *test_step
  release-package:
    <<: *default
    steps: *release
  release-rc-package:
    <<: *default
    steps: *release-rc

# Workflows
workflows:
  version: 2
  test_and_build:
    jobs:
      - codetest
      - release-package:
          filters:
            branches:
              only:
                - master
          requires:
            - codetest
      - release-rc-package:
          filters:
            branches:
              only:
                - /^release\/.*/
                - fix_f_string2
          requires:
            - codetest
