default: &default
  working_directory: ~/abeja-platform-sdk
  docker:
    - image: circleci/python:3.9

# Job Steps
test_step: &test_step
  - checkout
  - restore_cache:
      keys:
      - v1-dependencies-{{ checksum "poetry.lock" }}
  - run:
      name: Install Dependencies
      command: |
        sudo pip install poetry==1.2.2
        poetry config --local virtualenvs.in-project false
        poetry install
  - save_cache:
      key: v1-dependencies-{{ checksum "poetry.lock" }}
      paths:
        - .venv
  # - persist_to_workspace:
  #     root: .
  #     paths:
  #       - .venv
  - run:
      name: Test
      command: |
        make test
  # NOTE: need to fix test cases, because these are not stable.
  - run:
      name: Integration Test
      command: |
        make integration_test

install-release-dependencies: &install-release-dependencies
  run:
    name: Install Dependencies
    command: |
      sudo apt-get update
      poetry config --local virtualenvs.in-project false
      poetry install

replace-version: &replace-version
  run:
    name: replace version
    command: |
      ver=$(poetry version | cut -d ' ' -f 2)
      sed -i -e "s/VERSION = ['\"][^'\"]*['\"]/VERSION = \"$ver\"/" abeja/version.py

run-release: &run-release
  run:
    name: Deploy
    command: |
      sudo -E make release

trigger-system-test: &trigger-system-test
  run:
    name: TriggerSystemTest
    command: |
      poetry run python tools/trigger_build_system_test.py

release: &release
  - checkout
  - attach_workspace:
      at: .
  - *install-release-dependencies
  - *replace-version
  - *run-release
  - *trigger-system-test

release-rc: &release-rc
  - checkout
  - attach_workspace:
      at: .
  - *install-release-dependencies
  - run: sh .circleci/bump_version_rc.sh
  - *replace-version
  - *run-release
  - *trigger-system-test

# Jobs
version: 2
jobs:
  codetest:
    <<: *default
    steps: *test_step
  release-package:
    <<: *default
    steps: *release
  release-rc-package:
    <<: *default
    steps: *release-rc

# Workflows
workflows:
  version: 2
  test_and_build:
    jobs:
      - codetest
      - release-package:
          filters:
            branches:
              only:
                - master
          requires:
            - codetest
      - release-rc-package:
          filters:
            branches:
              only:
                - /^release\/.*/
          requires:
            - codetest
